image: bitnami/node:8

cache:
  paths:
    - node_modules/

before_script:
  - env DEBIAN_FRONTEND=noninteractive apt-get update -qq && env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq php < /dev/null > /dev/null
  - npm install --quiet --no-save eslint stylelint stylelint-config-standard stylelint-order stylelint-scss
  - node -v
  - npm -v
  - php -v

code_quality:
  script:
    - node node_modules/stylelint/bin/stylelint.js "./src/assets/styles/**/*.scss"
    - node node_modules/eslint/bin/eslint.js "./src/assets/scripts/**/*.js"
    - find . -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )
