image: jacob9230/linter

before_script:
  - rm package-lock.json; npm install --quiet --no-save stylelint-config-standard stylelint-order stylelint-scss
  - node -v
  - npm -v
  - php -v

code_quality:
  script:
    - stylelint "./src/assets/styles/**/*.scss"
    - eslint "./src/assets/scripts/**/*.js"
    - phplint "./src"
