image: jacob9230/linter

before_script:
  - npm install --no-package-lock --no-save --quiet stylelint stylelint-config-standard stylelint-order stylelint-scss
  - node -v
  - npm -v
  - php -v

code_quality:
  script:
    - stylelint "./src/assets/styles/**/*.scss"
    - eslint "./src/assets/scripts/**/*.js"
    - phplint "./src"
