image: jacob9230/linter

before_script:
  - node -v
  - npm -v
  - php -v

code_quality:
  script:
    - stylelint "./src/assets/styles/**/*.scss"
    - eslint "./src/assets/scripts/**/*.js"
    - phplint "./src"
